media:
  input: src/assets/images
  output: /

content:
  - name: categories
    label: Categories
    type: file
    path: src/data/categories.yml
    format: yaml
    list: true

    fields:
      - name: name
        label: Name
        type: string
        required: true

      - name: label
        label: Label
        type: string
        required: true

  - name: items
    label: Items
    type: file
    path: src/data/items.yml
    format: yaml
    list: true

    fields:
      - name: url
        label: URL
        type: string
        required: true

      - name: image
        label: Image
        type: image
        required: true
        options:
          media: images

      - name: text
        label: Alt text
        type: text
        required: true

      - name: category
        label: Category
        type: reference
        required: true
        options:
          collection: categories
          search: "name,label"
          value: "{name}"
          label: "{label}"